# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nathan Thoumine
email: thoum.nathan@gmail.com
author:
  name: Nathan Thoumine
  email: thoum.nathan@gmail.com
  links:
    - github: deicidia
    - linkedin: nathan-thoumine

description: >-
  Portfolio et Blog de Nathan Thoumine. Ingénieur IA Embarquée & Robotique. 
  Découvrez mes projets sur la vision par ordinateur, l'IA et le développement logiciel.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deicidia.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  deicidia
lang: fr
locale: fr_FR

# Social sharing image
social:
  name: Nathan Thoumine
  links:
    - https://github.com/deicidia
    - https://www.linkedin.com/in/nathan-thoumine/ # Placeholder, user might want to check this


# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  scans:
    output: true

# SASS configuration
sass:
  sass_dir: _sass
  style: compressed