# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nathan Thoumine
email: thoum.nathan@gmail.com
author: Nathan Thoumine
description: > # this means to ignore newlines until "baseurl:"
  Blog personnel de Nathan Thoumine. Ingénieur IA Embarquée & Robotique.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deicidia.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  deicidia
lang: fr

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  scans:
    output: true